/*
 * generated by Xtext 2.16.0
 */
package edu.kit.sdq.ide


/**
 * Use this class to register ide components.
 */
class CorrespondenceLanguageIdeModule extends AbstractCorrespondenceLanguageIdeModule {
}
